# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 164b81d38c0a4fae06edb1567caee7e92b0b68791a6251f58d8fa648a1f7c6ce62db836e0f63f3c82a850e39468da743b0347dd86efb233110ada9bb2e9ce89c

test:
  secret_key_base: 94e61ba9dfd9e52efef5364ed00170f4bcc13852370d7d0944473b1aedc2d9f6f9e4bd5b45af1757983f7b75e341b8dd60923329dd7198105ebb909eff37e473

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
